import type { Category, Trip } from '@/types/content';

/**
 * PLACEHOLDER SEED CONTENT — fictional trips used to build and demo the UI.
 * Replace with real client content (or a CMS source) at handoff. All prices,
 * names and images here are invented placeholders (see CLAUDE.md §2).
 *
 * In Phase 3 this data moves to `content/trips/*` files behind these same
 * repository functions; UI never changes.
 */

const PLACEHOLDER_IMAGE = {
  src: '/images/placeholder-trip.svg',
  alt: 'Placeholder scenery — replace with a licensed client photograph',
  width: 1200,
  height: 800,
};

export const categories: Category[] = [
  {
    key: 'tour',
    label: 'Tour',
    pluralLabel: 'Tours',
    slug: 'tours',
    intro: 'Guided, fully-inclusive tour packages at a comfortable pace.',
  },
  {
    key: 'trek',
    label: 'Trek',
    pluralLabel: 'Treks',
    slug: 'treks',
    intro: 'Multi-day guided treks with full camp support.',
  },
  {
    key: 'expedition',
    label: 'Expedition',
    pluralLabel: 'Expeditions',
    slug: 'expeditions',
    intro: 'High-altitude peak climbs with an experienced expedition team.',
  },
];

export const trips: Trip[] = [
  {
    slug: 'sample-valley-tour',
    title: 'Sample Valley Tour',
    category: 'tour',
    tags: ['culture', 'family'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder tour showing how a comfortable, guided valley itinerary is presented on a card and detail page.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 7,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    difficulty: 'easy',
    effort: 'easy',
    groupSizeMin: 4,
    groupSizeMax: 12,
    season: ['spring', 'autumn'],
    seasonNote: 'Spring blossom or autumn colour',
    accommodationNote: 'Comfort hotels with valley views',
    price: { amount: 1800, currency: 'USD', unit: 'per_person' },
    featured: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'sample-base-camp-trek',
    title: 'Sample Base Camp Trek',
    category: 'trek',
    tags: ['trekking'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder trek demonstrating altitude, difficulty and departure data on the reusable trip card.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 14,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 5150,
    difficulty: 'strenuous',
    effort: 'serious',
    groupSizeMax: 12,
    season: ['summer'],
    seasonNote: 'Summer departures',
    accommodationNote: 'Hotels either end, tents between',
    price: { amount: 2590, currency: 'USD', originalAmount: 2900, unit: 'per_person' },
    earlyBird: true,
    featured: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'sample-peak-expedition',
    title: 'Sample Peak Expedition',
    category: 'expedition',
    tags: ['expeditions', '6000m'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder expedition showing how a technical, high-altitude climb is summarised for prospective clients.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 23,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 6096,
    difficulty: 'technical',
    effort: 'serious',
    groupSizeMax: 8,
    season: ['summer'],
    seasonNote: 'Late June to mid-August',
    accommodationNote: 'Hotels either end, tents between',
    price: { amount: 4200, currency: 'USD', unit: 'per_person' },
    featured: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'coastal-heritage-tour',
    title: 'Coastal Heritage Tour',
    category: 'tour',
    tags: ['culture', 'history'],
    destinationSlugs: ['harbour-coast'],
    summary:
      'A relaxed placeholder tour tracing old harbour towns, markets and coastal forts at an unhurried pace.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 10,
    startCity: 'Gateway City',
    endCity: 'Harbour City',
    difficulty: 'easy',
    effort: 'easy',
    groupSizeMin: 2,
    groupSizeMax: 14,
    season: ['spring', 'autumn'],
    seasonNote: 'Mild spring or autumn weeks',
    accommodationNote: 'Boutique harbour-front stays',
    price: { amount: 2200, currency: 'USD', unit: 'per_person' },
    updatedAt: '2026-01-01',
  },
  {
    slug: 'desert-culture-tour',
    title: 'Desert Culture Tour',
    category: 'tour',
    tags: ['culture', 'family'],
    destinationSlugs: ['golden-desert'],
    summary:
      'A short placeholder tour of dune camps, caravan towns and night skies — an easy introduction to the region.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 5,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    difficulty: 'easy',
    effort: 'easy',
    groupSizeMin: 2,
    groupSizeMax: 12,
    season: ['winter', 'spring'],
    seasonNote: 'Cooler winter and spring months',
    accommodationNote: 'Comfort hotels and one desert camp',
    price: { amount: 1200, currency: 'USD', originalAmount: 1450, unit: 'per_person' },
    earlyBird: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'alpine-lakes-trek',
    title: 'Alpine Lakes Trek',
    category: 'trek',
    tags: ['trekking', 'lakes'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder moderate trek linking turquoise tarns and high meadows, with comfortable daily stages.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 9,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 4200,
    difficulty: 'moderate',
    effort: 'moderate',
    groupSizeMax: 12,
    season: ['summer', 'autumn'],
    seasonNote: 'Summer and early autumn',
    accommodationNote: 'Hotels either end, tents between',
    price: { amount: 1950, currency: 'USD', unit: 'per_person' },
    featured: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'high-pass-trek',
    title: 'High Pass Trek',
    category: 'trek',
    tags: ['trekking'],
    destinationSlugs: ['sample-region'],
    summary:
      'A serious placeholder crossing over a glaciated pass, for well-prepared trekkers with full crew support.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 18,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 5585,
    difficulty: 'strenuous',
    effort: 'serious',
    groupSizeMax: 10,
    season: ['summer'],
    seasonNote: 'Peak summer only',
    accommodationNote: 'Hotels either end, tents between',
    price: { amount: 3200, currency: 'USD', originalAmount: 3600, unit: 'per_person' },
    earlyBird: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'twin-summit-expedition',
    title: 'Twin Summit Expedition',
    category: 'expedition',
    tags: ['expeditions', '7000m'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder high-altitude double-header for experienced climbers, with a full expedition team and logistics.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 30,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 7100,
    difficulty: 'technical',
    effort: 'serious',
    groupSizeMax: 6,
    season: ['summer'],
    seasonNote: 'Summer weather window',
    accommodationNote: 'Hotels either end, tents between',
    price: { amount: 6800, currency: 'USD', unit: 'per_person' },
    priceOnRequest: true,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'spring-blossom-festival-tour',
    title: 'Spring Blossom Festival Tour',
    category: 'tour',
    tags: ['festival', 'culture', 'family'],
    destinationSlugs: ['sample-region', 'lakes-district'],
    summary:
      'A placeholder festival tour timed to the spring blossom, with village celebrations and orchard valleys.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 8,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    difficulty: 'easy',
    effort: 'easy',
    groupSizeMin: 2,
    groupSizeMax: 14,
    season: ['spring'],
    seasonNote: 'Blossom season only',
    accommodationNote: 'Comfort hotels with valley views',
    price: { amount: 1650, currency: 'USD', unit: 'per_person' },
    badge: 'Seasonal',
    featured: false,
    updatedAt: '2026-01-01',
  },
  {
    slug: 'highland-polo-festival-tour',
    title: 'Highland Polo Festival Tour',
    category: 'tour',
    tags: ['festival', 'culture'],
    destinationSlugs: ['sample-region'],
    summary:
      'A placeholder festival tour built around a high-altitude polo gathering and the surrounding valleys.',
    heroImage: PLACEHOLDER_IMAGE,
    durationDays: 11,
    startCity: 'Gateway City',
    endCity: 'Gateway City',
    maxAltitudeM: 3700,
    difficulty: 'moderate',
    effort: 'moderate',
    groupSizeMin: 2,
    groupSizeMax: 12,
    season: ['summer'],
    seasonNote: 'Festival dates in summer',
    accommodationNote: 'Hotels and one festival camp',
    price: { amount: 2400, currency: 'USD', unit: 'per_person' },
    badge: 'Popular',
    updatedAt: '2026-01-01',
  },
];
